version: '3.7'

x-common-variables:
  - &common_environment_variables
    API_PORT: 5050
    PLATFORM_IP: 'fuseki'
    LOG_DIR: "/mnt/log"
    LOG_LEVEL: "info"
    LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"

services:
  pipeline:
    hostname: pipeline
    container_name: pipeline
    build: ./pipeline
    ports:
      - '0.0.0.0:5050:5050'
    environment:
      <<: *common_environment_variables
    restart: always
    volumes: 
      - pipeline_input_data:/pipeline/data/
      - log:/mnt/log
    networks: [platform]
      
#Aqui es donde seria interesante crear una red compartida entre la plataforma en donde desplegar los rdf y el procesamiento de los datos
networks:
  platform:
    external:
      name: fuseki_platform

#No se como realizar un volumen compartido en el contenedor con la maquina local que sirve de host para evitar hacer la copia de documentos al contenedor.
volumes: 
  pipeline_input_data:
    driver: local
  log:
    driver: local
